### ISSUE TITLE
ANRs in Amplitude Experiments

### ISSUE THREAD

**Issue by davros1970** [amplitude/experiment-android-client#24]
```
implementation("com.amplitude:experiment-android-client:1.8.1")
```

With this version Crashlyitcs is showing ANR's  in the `get()` using the sample code from the [Quickstart Documentation](https://www.docs.developers.amplitude.com/experiment/sdks/android-sdk/).
```
        try {
            client.fetch(user).get()
        } catch (e: Exception) {
            e.printStackTrace()
        }
```

We had to bandaid this with a 4 second timeout.
```
        kotlin.runCatching {
            val client : ExperimentClient = Experiment.initialize(this, BuildConfig.amplitudeKey, config)

            // Added a 4 sec timeout due to production ANR's from this call previously when we did not have a timeout.
            client.fetch().get(TIMEOUT_AMPLITUDE_SETUP_SEC, TimeUnit.SECONDS)

            // etc.

        }.onFailure {
            Timber.e("Amplitude experiment failed to initialize")
        }
```

Any thoughts on why we are getting ANR's in the first place in production env?

**Comment by bgiori** [comment]
Hi @davros1970, thanks for submitting this issue, and sorry for the late reply, I've been out on PTO. 

The future returned by calling fetch() is resolved when a network request receives a response, fails, or times out. The default timeout is 10 seconds. If the user has a spotty network connection then the request may cause an ANR with the default timeout in place. 

Your approach with a custom timeout is the right direction. I suggest setting a timeout which is right for your particular application. You may also offload the fetch request to wait for the future to resolve off of the main thread. This will completely avoid ANRs all together, as the main thread will still be running while  the background thread is blocked.

The QuickStart guide in the dev docs puts the fetch in the main application code for the sake of removing a lot of boiler plate and keeping the snippet simple and concise. That said I would suggest  not blocking the main thread. 

Let me know if you have other questions!

**Comment by davros1970** [comment]
Thank you for the reply.

The 'right' timeout for any app using this MUST be < 5 sec to avoid the ANR. At a bare minimum the Getting Started needs that footnote.

The concern with thread offloading becomes 'When can I make the next API call into the Amplitude SDK if its not done fetching the configuration from the network?'  I guess apps would need to wrap all that in the AmplitudeRepository and have a `val isInitialized StateFlow<Boolean>` so they'll know when they can make their next call into the SDK cleanly.

**Comment by davros1970** [comment]
Thank you. You may close this issue given I have the information I need to move forward. Although it probably deserves some commentary in the documentation.

To finish the thought for the next person who encounters this, if you don't have an `isInitialized` flag of some sort, then your app risks using stale/incorrect experiment values. This can lead to "I set up experiment B but experiment A is running on the client. WHY?!" bugs.
