### ISSUE TITLE
Errors updating to 1.10.1

### ISSUE THREAD

**Issue by jt-gilkeson** [amplitude/experiment-android-client#35]
I get the following compile errors when I update for `1.10.0` to `1.10.1` also the `changelog` wasn't updated.  

```
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':data:debugCompileClasspath'.
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.amplitude:experiment-android-client:1.10.1.
```

**Comment by bgiori** [comment]
Hi @jt-gilkeson thanks for reporting this. The artifact was uploaded to the staging maven repo but never released to the central repo. I just released released it to MavenCentral, which should propagate and be available within one hour. 

Sorry for the inconvenience!
