### ISSUE TITLE
Passing an instanceName other than "\$default_instance" fails with TimeoutException

### ISSUE THREAD

**Issue by wilburx9** [amplitude/experiment-android-client#39]
When you pass an `instanceName` other than `"\$default_instance"` to the Configuration, it throws:

> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.util.concurrent.TimeoutException: Timed out waiting for Amplitude Analytics SDK to initialize. You should ensure that the analytics SDK is initialized prior to calling fetch()

This works:
```
val config = ExperimentConfig.builder()
      .build()
val experiment = Experiment.initializeWithAmplitudeAnalytics(app, $API_KEY  config,)
val user = ExperimentUser.builder()
.userId(userAuth0Id)
.deviceId(deviceIdFromAnalytics)
 .build()
experiment?.start(user)?.get()
```

This also works:
```
val config = ExperimentConfig.builder()
      .instanceName("\$default_instance")
      .build()
val experiment = Experiment.initializeWithAmplitudeAnalytics(app, $API_KEY  config,)
val user = ExperimentUser.builder()
.userId(userAuth0Id)
.deviceId(deviceIdFromAnalytics)
 .build()
experiment?.start(user)?.get()
```

But this throws the exception mentioned earlier:
```
val config = ExperimentConfig.builder()
      .instanceName("lorem_ipsum")
      .build()
val experiment = Experiment.initializeWithAmplitudeAnalytics(app, $API_KEY  config,)
val user = ExperimentUser.builder()
.userId(userAuth0Id)
.deviceId(deviceIdFromAnalytics)
 .build()
experiment?.start(user)?.get()
```
Why do I need multiple instances? This is e trying to solve #40, one for logged in session and the other before they log in.

I am using `v1.11.0`

**Comment by tyiuhc** [comment]
Hi @wilburx9, many thanks for reaching out. To help us better assist on this, please let us know:
1. Which analytics SDK, and what version of it are you using?
2. Are you setting the instance name of the analytics SDK to be the same as the one set in you experiment SDK?

**Comment by wilburx9** [comment]
1. "com.amplitude:android-sdk:2.36.1"
2. Nope, I don't set the instance name on the analytics SDK.

**Comment by tyiuhc** [comment]
On edit 2: Yes, this is the expected behavior. The SDK's instance name cannot be changed after instantiating.

**Comment by wilburx9** [comment]
Thanks for the clarification. Can the [documentation](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#configuration) be updated to reflect this behaviour? It currently says "You can dynamically set the configuration after initialization."
