### ISSUE TITLE
Unexpected Variant payload structure change on version 1.11.2

### ISSUE THREAD

**Issue by kevinguitar** [amplitude/experiment-android-client#44]
Hi, we're trying to migrate the SDK version, but we faced an unexpected variant payload structure changes, could you please point me out if it's expected? And where I can find the changelog related to this change, it seems fundamental and breaks almost all of our payload parsing. Thanks

Link to the config:
https://app.amplitude.com/experiment/bandlab/293492/config/36135/configure

Before (v1.10.1)
```
Variant(value=true, payload={"url":"https:\/\/bnd.la\/deals"}, expKey=null)
```

After (v1.11.2)
```
Variant(value=true, payload={url=https://bnd.la/deals}, expKey=null, key=true, metadata=null)
```

**Comment by victorkifer** [comment]
We're experiencing the same issue after upgrading. Moreover, the payload is not stable, in some cases it's returned as String and in other cases as a LinkedHashMap.
![Screenshot 2023-11-09 at 16 20 53](https://github.com/amplitude/experiment-android-client/assets/5956780/bc65ba31-95d8-4924-a366-55af1cde5dba)
![Screenshot 2023-11-09 at 16 21 09](https://github.com/amplitude/experiment-android-client/assets/5956780/5da7a0fe-eb17-45ac-a264-3fb348f46aee)

**Comment by kevinguitar** [comment]
Seems alright, thanks 🙏  I'm good to close the issue
